export const APP_LOADER = 'APP_LOADER';

export const AUTH_NAVIGATOR = 'AUTH_NAVIGATOR';

export const MAIN_NAVIGATOR = 'MAIN_NAVIGATOR';
export const router = {
    APP_LOADER: 'APP_LOADER',
    AUTH_NAVIGATOR: 'AUTH_NAVIGATOR',
    MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    REGISTER_BY: 'REGISTER_BY',
    REGISTER_BY_EMAIL: 'REGISTER_BY_EMAIL',
    FORGET_PASSWORD: 'FORGET_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_OLD_PASSWORD: 'CHANGE_OLD_PASSWORD',
    CHANGE_LAUGUAGE: 'CHANGE_LAUGUAGE',
    FIELD: 'FIELD',
    ACCOUNT_INFO: 'ACCOUNT_INFO',
    USER_INFO: 'USER_INFO',
    SUCCESS: 'SUCCESS',
    OTP: 'OTP',
    MENU: 'MENU',
    MAIN: 'MAIN',
    HOME: 'HOME',
    TAI_NGUYEN: 'TAI_NGUYEN',
}