export const APP_LOADER = 'APP_LOADER';

export const AUTH_NAVIGATOR = 'AUTH_NAVIGATOR';

export const MAIN_NAVIGATOR = 'MAIN_NAVIGATOR';
export const router = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    REGISTER_BY: 'REGISTER_BY',
    REGISTER_BY_EMAIL: 'REGISTER_BY_EMAIL',
    FORGET_PASSWORD: 'FORGET_PASSWORD',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    ACCOUNT_INFO: 'ACCOUNT_INFO',
    SUCCESS: 'SUCCESS',
    OTP: 'OTP',
    MAIN: 'MAIN',
    HOME: 'HOME',
    TAI_NGUYEN: 'TAI_NGUYEN',
}